"""
Information Management Agent.

Produces the Situation Report (SitRep) — the signature UNDAC information product
— synthesising the incident, assessment, coordination and logistics picture into
a shareable narrative. Uses Claude for the narrative when available, otherwise a
structured template that mirrors the OCHA SitRep format.

UNDAC mapping: F.1 Information Management; F.3 Reporting, IM products and
analysis outputs.
"""
from __future__ import annotations
import datetime as _dt

from ..models import (DisasterIncident, Assessment, CoordinationPlan,
                      LogisticsPlan, SitRep)
from .. import llm


def _template_sitrep(number, incident, assessment, coordination, logistics) -> str:
    now = _dt.datetime.utcnow().strftime("%d %b %Y %H:%M UTC")
    loc = incident.location or "Unknown location"
    lines = []
    lines.append(f"## SITUATION REPORT No. {number} — {incident.disaster_type} · {loc}")
    lines.append(f"*Issued {now} · UNDAC / OSOCC · Severity: **{assessment.severity_score}** "
                 f"({assessment.severity_index}/100)*")
    lines.append("")
    def fig(val, label):
        return f"{val:,} ({label})" if val is not None else "not estimated"

    lines.append("### 1. Highlights")
    lines.append(f"- {incident.disaster_type} affecting **{loc}**.")
    lines.append(f"- People affected: **{fig(assessment.affected_population, assessment.affected_label or 'estimate')}**.")
    lines.append(f"- Displaced: **{fig(assessment.displaced_estimate, assessment.displaced_label or 'reported')}**.")
    if assessment.fatalities_estimate is not None or assessment.fatalities_label:
        lines.append(f"- Casualties: **{fig(assessment.fatalities_estimate, assessment.fatalities_label or 'estimate') if assessment.fatalities_estimate is not None else assessment.fatalities_label}**.")
    lines.append(f"- Life-saving window: ~**{assessment.golden_hours}h** "
                 f"(hazard ref {assessment.hazard_ref}).")
    lines.append("")
    lines.append("### 2. Situation Overview")
    lines.append(f"Severity assessed as **{assessment.severity_score}** "
                 f"({assessment.severity_index}/100). Basis: {assessment.severity_basis}.")
    if assessment.data_sources:
        srcs = ", ".join(s.get("name", "") for s in assessment.data_sources)
        lines.append(f"*Data sources: {srcs}.*")
    if assessment.secondary_hazards:
        lines.append(f"Secondary hazards to monitor: {', '.join(assessment.secondary_hazards)}.")
    lines.append("")
    lines.append("### 3. Priority Needs by Sector")
    for sn in assessment.sector_needs:
        lines.append(f"- **{sn.sector}** ({sn.priority}): {sn.rationale}")
    lines.append("")
    lines.append("### 4. Coordination (OSOCC)")
    if coordination:
        lines.append(f"OSOCC activated. Lead clusters: {', '.join(coordination.lead_clusters)}.")
        lines.append("")
        lines.append("**3W — Who does What Where:**")
        lines.append("")
        lines.append("| Who | What | Where | Sector | Status |")
        lines.append("|-----|------|-------|--------|--------|")
        for e in coordination.three_w:
            lines.append(f"| {e.who} | {e.what} | {e.where} | {e.sector} | {e.status} |")
        lines.append("")
        lines.append("**Coordination gaps:**")
        for g in coordination.coordination_gaps:
            lines.append(f"- {g}")
    lines.append("")
    lines.append("### 5. Logistics & Resources")
    if logistics:
        lines.append(logistics.summary)
        lines.append("")
        lines.append("| Resource | Available | Location(s) | Requested | Gap | Status |")
        lines.append("|----------|-----------|-------------|-----------|-----|--------|")
        for l in logistics.lines:
            req = f"{l.requested:,}" if l.requested is not None else "—"
            gap = f"{l.gap:,}" if l.gap is not None else "—"
            loc = "; ".join(l.locations) if l.locations else "—"
            lines.append(f"| {l.label or l.item} | {l.available:,} {l.unit} | {loc} | {req} | {gap} | {l.status} |")
    lines.append("")
    lines.append("### 6. Priority Actions (next operational period)")
    for a in assessment.priority_actions:
        lines.append(f"- {a}")
    if coordination:
        for t in coordination.tasking:
            lines.append(f"- {t}")
    lines.append("")
    lines.append("*Generated by the UNDAC Crisis Coordinator agentic platform. "
                 "For coordination use — verify against ground truth before action.*")
    return "\n".join(lines)


def run_im_agent(number, incident: DisasterIncident, assessment: Assessment,
                 coordination: CoordinationPlan, logistics: LogisticsPlan,
                 emit=None) -> SitRep:
    def say(msg):
        if emit:
            emit("InfoManagement", msg)

    say("Compiling Situation Report (SitRep) from the operating picture…")
    body = _template_sitrep(number, incident, assessment, coordination, logistics)

    # Optional: ask Claude to write an executive headline for the SitRep
    aff = (f"{assessment.affected_population:,} affected"
           if assessment.affected_population is not None else "impact being assessed")
    headline = (f"{assessment.severity_score} {incident.disaster_type} in "
                f"{incident.location} — {aff}")
    llm_head = llm.complete(
        system="You are an OCHA Information Management Officer writing SitRep headlines.",
        user=(f"Write a single concise (<=20 word) situation-report headline for a "
              f"{assessment.severity_score} {incident.disaster_type} in {incident.location} "
              f"({aff}). Do not state figures that are not given. No quotes."),
        max_tokens=60,
    )
    if llm_head:
        headline = llm_head.strip().strip('"')
        say("Claude drafted the executive headline.")

    say("SitRep ready.")
    return SitRep(
        number=number,
        title=f"{incident.disaster_type} · {incident.location} · SitRep #{number}",
        headline=headline,
        body_markdown=body,
    )
